In [6]:
import pandas as pd

In [9]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Note: you may need to restart the kernel to use updated packages.

In [10]:
df = pd.read_excel("data/약제급여목록및급여상한금액표_(2024.5.1.)(22,850)_공개용.xlsx")
df.head()

,연번,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
0,1,내복,112,130830ASY,chloral hydrate 9.5g(0.1g/mL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,내복,112,130830ASY,645302132,포크랄시럽(포수클로랄)_(9.5g/95mL),한림제약(주),95(1),mL/병,129,전문,NaN,645302130.0
2,3,내복,112,130832ASY,chloral hydrate 1g(0.1g/mL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,내복,112,130832ASY,645302133,포크랄시럽(포수클로랄)_(1g/10mL),한림제약(주),10,mL/병,1260,전문,NaN,NaN
4,5,내복,112,130833ASY,chloral hydrate 0.5g(0.1g/mL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# 제품코드가 숫자 형식인것만 필터링
df = df[df['제품코드'].str.isnumeric()]

In [13]:
df.head()

,연번,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
1,2,내복,112,130830ASY,645302132,포크랄시럽(포수클로랄)_(9.5g/95mL),한림제약(주),95(1),mL/병,129,전문,NaN,645302130.0
3,4,내복,112,130832ASY,645302133,포크랄시럽(포수클로랄)_(1g/10mL),한림제약(주),10,mL/병,1260,전문,NaN,NaN
5,6,내복,112,130833ASY,645302135,포크랄시럽(포수클로랄)_(0.5g/5mL),한림제약(주),5,mL/병,847,전문,NaN,NaN
7,8,내복,112,149203ATB,651904420,명세핀정3밀리그램(독세핀염산염)_(3.39mg/1정),명인제약(주),1,정,96,전문,NaN,NaN
8,9,내복,112,149203ATB,640006660,사일레노정3밀리그램(독세핀염산염)_(3.39mg/1정),에이치케이이노엔(주),1,정,97,전문,NaN,NaN

In [14]:
df['제품명'] = df['제품명'].str.split('_').str[0]

In [15]:
df.head()

,연번,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
1,2,내복,112,130830ASY,645302132,포크랄시럽(포수클로랄),한림제약(주),95(1),mL/병,129,전문,NaN,645302130.0
3,4,내복,112,130832ASY,645302133,포크랄시럽(포수클로랄),한림제약(주),10,mL/병,1260,전문,NaN,NaN
5,6,내복,112,130833ASY,645302135,포크랄시럽(포수클로랄),한림제약(주),5,mL/병,847,전문,NaN,NaN
7,8,내복,112,149203ATB,651904420,명세핀정3밀리그램(독세핀염산염),명인제약(주),1,정,96,전문,NaN,NaN
8,9,내복,112,149203ATB,640006660,사일레노정3밀리그램(독세핀염산염),에이치케이이노엔(주),1,정,97,전문,NaN,NaN

In [16]:
df = df.drop(columns=['연번'])

In [17]:
df

,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
1,내복,112,130830ASY,645302132,포크랄시럽(포수클로랄),한림제약(주),95(1),mL/병,129,전문,NaN,645302130.0
3,내복,112,130832ASY,645302133,포크랄시럽(포수클로랄),한림제약(주),10,mL/병,1260,전문,NaN,NaN
5,내복,112,130833ASY,645302135,포크랄시럽(포수클로랄),한림제약(주),5,mL/병,847,전문,NaN,NaN
7,내복,112,149203ATB,651904420,명세핀정3밀리그램(독세핀염산염),명인제약(주),1,정,96,전문,NaN,NaN
8,내복,112,149203ATB,640006660,사일레노정3밀리그램(독세핀염산염),에이치케이이노엔(주),1,정,97,전문,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
30345,외용,821,630901CSI,641605801,인스타닐나잘스프레이50마이크로그램(펜타닐시트르산염),(주)대웅제약,10,회/통,61000,전문,NaN,641605800.0
30347,기타,332,238201DPD,658601560,이연트롬빈동결건조분말5000단위,이연제약(주),1,병,7633,전문,NaN,NaN
30349,기타,341,393301DPD,646601660,크린카트에이(무수탄산나트륨),(주)박스터,1,관,산정불가,전문,NaN,NaN
30351,기타,341,408401DPD,646601680,크린카트씨(무수구연산),(주)박스터,1,관,산정불가,전문,NaN,NaN
30353,기타,732,408501DMS,641000020,쓰리엠스테리-가스EO카트리지,한국쓰리엠(주),1,키트,산정불가,일반,NaN,NaN

In [19]:
df.to_excel("data/전처리데이터/현재급여가능의약품.xlsx")

### 확인

In [20]:
data = pd.read_excel("data/전처리데이터/현재급여가능의약품.xlsx")
data

,Unnamed: 0,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
0,1,내복,112,130830ASY,645302132,포크랄시럽(포수클로랄),한림제약(주),95(1),mL/병,129,전문,NaN,645302130.0
1,3,내복,112,130832ASY,645302133,포크랄시럽(포수클로랄),한림제약(주),10,mL/병,1260,전문,NaN,NaN
2,5,내복,112,130833ASY,645302135,포크랄시럽(포수클로랄),한림제약(주),5,mL/병,847,전문,NaN,NaN
3,7,내복,112,149203ATB,651904420,명세핀정3밀리그램(독세핀염산염),명인제약(주),1,정,96,전문,NaN,NaN
4,8,내복,112,149203ATB,640006660,사일레노정3밀리그램(독세핀염산염),에이치케이이노엔(주),1,정,97,전문,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22845,30345,외용,821,630901CSI,641605801,인스타닐나잘스프레이50마이크로그램(펜타닐시트르산염),(주)대웅제약,10,회/통,61000,전문,NaN,641605800.0
22846,30347,기타,332,238201DPD,658601560,이연트롬빈동결건조분말5000단위,이연제약(주),1,병,7633,전문,NaN,NaN
22847,30349,기타,341,393301DPD,646601660,크린카트에이(무수탄산나트륨),(주)박스터,1,관,산정불가,전문,NaN,NaN
22848,30351,기타,341,408401DPD,646601680,크린카트씨(무수구연산),(주)박스터,1,관,산정불가,전문,NaN,NaN
22849,30353,기타,732,408501DMS,641000020,쓰리엠스테리-가스EO카트리지,한국쓰리엠(주),1,키트,산정불가,일반,NaN,NaN

In [21]:
data[data['제품명'] == '애드칼정']

,Unnamed: 0,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
12820,14914,내복,321,303200ATB,643301810,애드칼정,(주)종근당,1,정,50,일반,NaN,NaN

In [23]:
data[data['제품코드'] == 624200070]

,Unnamed: 0,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
14837,17421,내복,396,706900ATB,624200070,다파글립정10/100밀리그램,지엘팜텍(주),1,정,846,전문,NaN,NaN

In [24]:
data[data['제품명'] == '액피오정15밀리그램(피오글리타존염산염)']

,Unnamed: 0,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
13891,16269,내복,396,431901ATB,642101210,액피오정15밀리그램(피오글리타존염산염),(주)유한양행,1,정,647,전문,NaN,NaN

In [25]:
data[data['제품명'] == '와이투아트라셋정']

Empty DataFrame
Columns: [Unnamed: 0, 투여, 분류, 주성분코드, 제품코드, 제품명, 업체명, 규격, 단위, 상한금액, 전일, 비고, 목록정비전코드]
Index: []

In [26]:
data[data['제품코드'] == 72400350]

Empty DataFrame
Columns: [Unnamed: 0, 투여, 분류, 주성분코드, 제품코드, 제품명, 업체명, 규격, 단위, 상한금액, 전일, 비고, 목록정비전코드]
Index: []

In [27]:
data[data['제품명'] == '플로틴캡슐10밀리그램(플루옥세틴염산염)']

Empty DataFrame
Columns: [Unnamed: 0, 투여, 분류, 주성분코드, 제품코드, 제품명, 업체명, 규격, 단위, 상한금액, 전일, 비고, 목록정비전코드]
Index: []

In [28]:
data[data['제품명'] == '액티엠정(피오글리타존염산염)']

,Unnamed: 0,투여,분류,주성분코드,제품코드,제품명,업체명,규격,단위,상한금액,전일,비고,목록정비전코드
13858,16236,내복,396,431901ATB,669802010,액티엠정(피오글리타존염산염),구주제약(주),1,정,551,전문,NaN,NaN

In [29]:
data[data['제품명'] == '나프원큐연질캡슐(나프록센)']

Empty DataFrame
Columns: [Unnamed: 0, 투여, 분류, 주성분코드, 제품코드, 제품명, 업체명, 규격, 단위, 상한금액, 전일, 비고, 목록정비전코드]
Index: []

In [31]:
data[data['제품코드'] == 626501300]

Empty DataFrame
Columns: [Unnamed: 0, 투여, 분류, 주성분코드, 제품코드, 제품명, 업체명, 규격, 단위, 상한금액, 전일, 비고, 목록정비전코드]
Index: []

In [32]:
data[data['제품명'] == '크리스탈이부프로펜주']

Empty DataFrame
Columns: [Unnamed: 0, 투여, 분류, 주성분코드, 제품코드, 제품명, 업체명, 규격, 단위, 상한금액, 전일, 비고, 목록정비전코드]
Index: []

In [33]:
data[data['제품코드'] == 52701431]

Empty DataFrame
Columns: [Unnamed: 0, 투여, 분류, 주성분코드, 제품코드, 제품명, 업체명, 규격, 단위, 상한금액, 전일, 비고, 목록정비전코드]
Index: []